server:
  port: 8081
spring:    
  application:
    name: PostalCodeCoordinates
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
logging:
  level:
    org.springframework.web: debug
    com.practice.postalcodeCoordinates: debug